FROM ubuntu
LABEL autor=Edgar
RUN apt-get update
RUN apt-get install nginx -y
WORKDIR /var/www/html/
#COPY ./index.html /var/www/html
#COPY ./script.js /var/www/html
COPY . /var/www/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
