FROM ubuntu
LABEL autor=Edgar
RUN apt-get update
RUN apt-get install nginx -y
WORKDIR /var/www/html/
COPY /home/edgar/DevOps/docker/files/index.html /var/www/html
COPY /home/edgar/DevOps/docker/files/script.js /var/www/html
COPY /home/edgar/DevOps/docker/files/styles.css /var/www/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
