version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000" 
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    profiles:
      - web1
    depends_on:
      - db

  db:
    image: postgres:13 
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
