FROM ubuntu 
LABEL autor=Edgar
ADD testdocker.tar.gz /app/test/ 
#ENTRYPOINT ["echo","hello my docker"]
#CMD ["sh","-c","ls | grep bin"]
#ENTRYPOINT ["echo"]
CMD ["echo","helloworld"]
CMD ["nginx","-g","daemon off;"]
